kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "common.names.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    component: node
spec:
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      component: node
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        component: node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instance.hetzner.cloud/is-root-server
                operator: NotIn
                values:
                - "true"
      containers:
        - name: csi-node-driver-registrar
          image: {{ .Values.node.registrar.image }}:{{ .Values.node.registrar.tag }}
          args:
            - --kubelet-registration-path={{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/socket
          volumeMounts:
            - name: plugin-dir
              mountPath: /run/csi
            - name: registration-dir
              mountPath: /registration
        - command:
          - /bin/hcloud-csi-driver-node
          name: hcloud-csi-driver
          env:
            - name: CSI_ENDPOINT
              value: unix:///run/csi/socket
            - name: METRICS_ENDPOINT
              value: 0.0.0.0:9189
            - name: ENABLE_METRICS
              value: "{{ .Values.metrics.enabled }}"
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 2
          ports:
            {{- if .Values.metrics.enabled }}
            - containerPort: 9189
              name: metrics
            {{- end }}
            - name: healthz
              containerPort: 9808
              protocol: TCP
          securityContext:
            privileged: true
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}
              mountPropagation: Bidirectional
            - name: plugin-dir
              mountPath: /run/csi
            - name: device-dir
              mountPath: /dev
          securityContext:
            privileged: true
        - name: liveness-probe
          imagePullPolicy: Always
          image: {{ .Values.node.livenessprobe.image }}:{{ .Values.node.livenessprobe.tag }}
          volumeMounts:
            - mountPath: /run/csi
              name: plugin-dir
      tolerations:
        - effect: NoExecute
          operator: Exists
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
      volumes:
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins/csi.hetzner.cloud/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: {{ .Values.node.kubeletPath | default "/var/lib/kubelet" }}/plugins_registry/
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
